GetAway/Models/Administrator.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace GetAway.Models
{
    public class Administrator
    {
        [Required]
        public int Id { get; set; }

        [Required]
        [Display(Name = "Username")]
        [StringLength(255)]
        public string AdministratorName { get; set; }

        [Required]
        [Display(Name = "Password")]
        [StringLength(32)]
        public string Password { get; set; }
    }
}

GetAway/Controllers/AdministratorsController.cs
using GetAway.Models;
using GetAway.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GetAway.Controllers
{
    public class AdministratorsController : Controller
    {
        private ApplicationDbContext _context;

        public AdministratorsController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        // GET: Administrators
        public ActionResult Index()
        {

            return View();
        }

        public ActionResult NewPackage()
        {
            return View();
        }

        
        // Needs validation for file type
        public ActionResult AddPackage(Package Package, HttpPostedFileBase PackagePicture1, HttpPostedFileBase PackagePicture2, HttpPostedFileBase PackagePicture3, HttpPostedFileBase PackagePicture4, HttpPostedFileBase PackagePicture5, HttpPostedFileBase PackagePicture6)
        {
            if (ModelState.IsValid)
            {
                if (PackagePicture1 != null)
                {
                    PackagePicture1.SaveAs(Server.MapPath("~/Images/Packages/") + PackagePicture1.FileName);
                    PackagePicture2.SaveAs(Server.MapPath("~/Images/Packages/") + PackagePicture2.FileName);
                    PackagePicture3.SaveAs(Server.MapPath("~/Images/Packages/") + PackagePicture3.FileName);
                    PackagePicture4.SaveAs(Server.MapPath("~/Images/Packages/") + PackagePicture4.FileName);
                    PackagePicture5.SaveAs(Server.MapPath("~/Images/Packages/") + PackagePicture5.FileName);
                    PackagePicture6.SaveAs(Server.MapPath("~/Images/Packages/") + PackagePicture6.FileName);

                    string path1 = Path.Combine(Server.MapPath("~/Images/Packages/"), Path.GetFileName(PackagePicture1.FileName));
                    string path2 = Path.Combine(Server.MapPath("~/Images/Packages/"), Path.GetFileName(PackagePicture2.FileName));
                    string path3 = Path.Combine(Server.MapPath("~/Images/Packages/"), Path.GetFileName(PackagePicture3.FileName));
                    string path4 = Path.Combine(Server.MapPath("~/Images/Packages/"), Path.GetFileName(PackagePicture4.FileName));
                    string path5 = Path.Combine(Server.MapPath("~/Images/Packages/"), Path.GetFileName(PackagePicture5.FileName));
                    string path6 = Path.Combine(Server.MapPath("~/Images/Packages/"), Path.GetFileName(PackagePicture6.FileName));

                    var pp1Path = "/Images/Packages/" + PackagePicture1.FileName;
                    var pp2Path = "/Images/Packages/" + PackagePicture2.FileName;
                    var pp3Path = "/Images/Packages/" + PackagePicture3.FileName;
                    var pp4Path = "/Images/Packages/" + PackagePicture4.FileName;
                    var pp5Path = "/Images/Packages/" + PackagePicture5.FileName;
                    var pp6Path = "/Images/Packages/" + PackagePicture6.FileName;

                    Package.PackagePicture1 = pp1Path;
                    Package.PackagePicture2 = pp2Path;
                    Package.PackagePicture3 = pp3Path;
                    Package.PackagePicture4 = pp4Path;
                    Package.PackagePicture5 = pp5Path;
                    Package.PackagePicture6 = pp6Path;

                }

                _context.Package.Add(Package);
            try
            {
                _context.SaveChanges();
            }
            catch (DbEntityValidationException dbve)
            {
                Console.WriteLine(dbve);
            }

        }
            return RedirectToAction("NewPackage");
    }

        public ActionResult NewHotel()
        {
            return View();
        }

        // Needs validation for file type
        public ActionResult AddHotel(Hotel Hotel, HttpPostedFileBase HotelPicture1, HttpPostedFileBase HotelPicture2, HttpPostedFileBase HotelPicture3, HttpPostedFileBase HotelPicture4, HttpPostedFileBase HotelPicture5, HttpPostedFileBase HotelPicture6)
        {
            if(ModelState.IsValid)
            {
                if(HotelPicture1 != null)
                {
                    HotelPicture1.SaveAs(Server.MapPath("~/Images/Hotels/") + HotelPicture1.FileName);
                    HotelPicture2.SaveAs(Server.MapPath("~/Images/Hotels/") + HotelPicture2.FileName);
                    HotelPicture3.SaveAs(Server.MapPath("~/Images/Hotels/") + HotelPicture3.FileName);
                    HotelPicture4.SaveAs(Server.MapPath("~/Images/Hotels/") + HotelPicture4.FileName);
                    HotelPicture5.SaveAs(Server.MapPath("~/Images/Hotels/") + HotelPicture5.FileName);
                    HotelPicture6.SaveAs(Server.MapPath("~/Images/Hotels/") + HotelPicture6.FileName);

                    string path1 = Path.Combine(Server.MapPath("~/Images/Hotels/"), Path.GetFileName(HotelPicture1.FileName));
                    string path2 = Path.Combine(Server.MapPath("~/Images/Hotels/"), Path.GetFileName(HotelPicture2.FileName));
                    string path3 = Path.Combine(Server.MapPath("~/Images/Hotels/"), Path.GetFileName(HotelPicture3.FileName));
                    string path4 = Path.Combine(Server.MapPath("~/Images/Hotels/"), Path.GetFileName(HotelPicture4.FileName));
                    string path5 = Path.Combine(Server.MapPath("~/Images/Hotels/"), Path.GetFileName(HotelPicture5.FileName));
                    string path6 = Path.Combine(Server.MapPath("~/Images/Hotels/"), Path.GetFileName(HotelPicture6.FileName));

                    var hp1Path = "/Images/Hotels/" + HotelPicture1.FileName;
                    var hp2Path = "/Images/Hotels/" + HotelPicture2.FileName;
                    var hp3Path = "/Images/Hotels/" + HotelPicture3.FileName;
                    var hp4Path = "/Images/Hotels/" + HotelPicture4.FileName;
                    var hp5Path = "/Images/Hotels/" + HotelPicture5.FileName;
                    var hp6Path = "/Images/Hotels/" + HotelPicture6.FileName;

                    Hotel.HotelPicture1 = hp1Path;
                    Hotel.HotelPicture2 = hp2Path;
                    Hotel.HotelPicture3 = hp3Path;
                    Hotel.HotelPicture4 = hp4Path;
                    Hotel.HotelPicture5 = hp5Path;
                    Hotel.HotelPicture6 = hp6Path;

                }

                _context.Hotel.Add(Hotel);
                try
                {
                    _context.SaveChanges();
                }
                catch (DbEntityValidationException dbve)
                {
                    Console.WriteLine(dbve);
                }

            }
            return RedirectToAction("NewHotel");
        }

        public ActionResult NewRoom()
        {
            var HotelList = _context.Hotel.ToList();
            var viewModel = new AddRoomViewModel
            {
                Hotel = HotelList
            };
            return View(viewModel);
        }

        // Needs validation for file type
        public ActionResult AddRoom(Room Room, HttpPostedFileBase rp1, HttpPostedFileBase rp2, HttpPostedFileBase rp3)
        {
            if(ModelState.IsValid)
            {
                if(rp1 != null)
                {
                    rp1.SaveAs(Server.MapPath("~/Images/Rooms/") + rp1.FileName);
                    rp2.SaveAs(Server.MapPath("~/Images/Rooms/") + rp2.FileName);
                    rp3.SaveAs(Server.MapPath("~/Images/Rooms/") + rp3.FileName);

                    string path1 = Path.Combine(Server.MapPath("~/Images/Rooms/"), Path.GetFileName(rp1.FileName));
                    string path2 = Path.Combine(Server.MapPath("~/Images/Rooms/"), Path.GetFileName(rp2.FileName));
                    string path3 = Path.Combine(Server.MapPath("~/Images/Rooms/"), Path.GetFileName(rp3.FileName));

                    var rp1Path = "/Images/Rooms/" + rp1.FileName;
                    var rp2Path = "/Images/Rooms/" + rp2.FileName;
                    var rp3Path = "/Images/Rooms/" + rp3.FileName;

                    Room.RoomPicture1 = rp1Path;
                    Room.RoomPicture2 = rp2Path;
                    Room.RoomPicture3 = rp3Path;
                    Room.RoomStatus = 0;
                }
                _context.Room.Add(Room);

                try
                {
                    _context.SaveChanges();
                }
                catch (DbEntityValidationException dbve)
                {
                    Console.WriteLine(dbve);
                }
            }

            return RedirectToAction("NewRoom");
        }
    }
}

GetAway/Views/Administrators/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Index</h2>

GetAway/Views/Administrators/NewHotel.cshtml
@model GetAway.Models.Hotel
@{
    ViewBag.Title = "AddHotel";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />

<h2>Add Hotel</h2>

@using (Html.BeginForm("AddHotel", "Administrators", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{
    <br>

    <div class="form-group">
        @Html.LabelFor(m => m.HotelName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.HotelName, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.HotelRooms, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.HotelRooms, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.HotelContactNumber, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.HotelContactNumber, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.HotelAddress, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextAreaFor(m => m.HotelAddress, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.HotelDescription, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextAreaFor(m => m.HotelDescription, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.HotelRating, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.HotelRating, new { @class = "form-control" })
        </div>
    </div>


    @*
         Vertical Line
        <div style="border-left:1px solid #000;height:500px"></div>
    *@

    <div class="form-group">
        @Html.LabelFor(m => m.HotelPicture1, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.HotelPicture1, new { @type = "file" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.HotelPicture2, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.HotelPicture2, new { @type = "file" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.HotelPicture3, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.HotelPicture3, new { @type = "file" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.HotelPicture4, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.HotelPicture4, new { @type = "file" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.HotelPicture5, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.HotelPicture5, new { @type = "file" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.HotelPicture6, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.HotelPicture6, new { @type = "file" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Add Hotel" />
        </div>
    </div>
}

GetAway/Views/Administrators/NewPackage.cshtml
@model GetAway.Models.Package
@{
    ViewBag.Title = "NewPackage";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2>Add New Package</h2>

@using (Html.BeginForm("AddPackage", "Administrators", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{
    <br>

    <div class="form-group">
        @Html.LabelFor(m => m.PackageName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.PackageName, new { @class = "form-control"})
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.PackageType, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.PackageType, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.PackageDuration, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.PackageDuration, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Rate, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Rate, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Discount, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Discount, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.PackageActivities, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextAreaFor(m => m.PackageActivities, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.PackageDescription, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextAreaFor(m => m.PackageDescription, new { @class = "form-control" })
        </div>
    </div>


    @* 
         Vertical Line
        <div style="border-left:1px solid #000;height:500px"></div>
    *@

    <div class="form-group" >
        @Html.LabelFor(m => m.PackagePicture1, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.PackagePicture1, new { @type = "file" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.PackagePicture2, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.PackagePicture2, new { @type = "file" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.PackagePicture3, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.PackagePicture3, new { @type = "file" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.PackagePicture4, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.PackagePicture4, new { @type = "file" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.PackagePicture5, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.PackagePicture5, new { @type = "file" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.PackagePicture6, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.PackagePicture6, new { @type = "file" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Add Package" />
        </div>
    </div>
}

GetAway/Views/Administrators/NewRoom.cshtml
@model GetAway.ViewModels.AddRoomViewModel
@{
    ViewBag.Title = "AddRoom";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />

<h2>AddRoom</h2>


@using (Html.BeginForm("AddRoom", "Administrators", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{
    <br>

    <div class="form-group">
        @Html.LabelFor(m => m.Room.RoomNumber, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Room.RoomNumber, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Room.HotelID, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.Room.HotelID, new SelectList(Model.Hotel,"Id","HotelName"), "Select Hotel", new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Room.RoomType, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Room.RoomType, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Room.RoomRate, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Room.RoomRate, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Room.RoomDescription, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextAreaFor(m => m.Room.RoomDescription, new { @class = "form-control" })
        </div>
    </div>


    @*
         Vertical Line
        <div style="border-left:1px solid #000;height:500px"></div>
    *@

    <div class="form-group">
        @Html.LabelFor(m => m.Room.RoomPicture1, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @*@Html.TextBoxFor(m => m.Room.RoomPicture1, new { @type = "file", name = "Room_RoomPicture1" })*@
            <input type="file" name="rp1" id="rp1">
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Room.RoomPicture2, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @*@Html.TextBoxFor(m => m.Room.RoomPicture2, new { @type = "file" })*@
            <input type="file" name="rp2" id="rp2">
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Room.RoomPicture3, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @*@Html.TextBoxFor(m => m.Room.RoomPicture3, new { @type = "file" })*@
            <input type="file" name="rp3" id="rp3">
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Add Room" />
        </div>
    </div>
}